
import { GoogleGenAI } from "@google/genai";
import { ArtStyle, ComplexityLevel } from "../types";

export async function transformToIllustration(
  base64Image: string, 
  style: ArtStyle = 'classic', 
  complexity: ComplexityLevel = 'medium'
): Promise<string> {
  // Always create a new instance to ensure the latest API key is used
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
  
  // Extract mime type and data from base64
  const matches = base64Image.match(/^data:([a-zA-Z0-9]+\/[a-zA-Z0-9-.+]+);base64,(.+)$/);
  if (!matches || matches.length !== 3) {
    throw new Error("Invalid image format");
  }
  
  const mimeType = matches[1];
  const imageData = matches[2];

  // --- STYLE CONFIGURATION ---
  const stylePrompts: Record<ArtStyle, string> = {
    classic: "Paint by Numbers style. Clean, distinct organic shapes. Balanced composition.",
    stained_glass: "Stained Glass window style. Thick, geometric black leading lines. Jewel-tone flat colors. Angular segmentation.",
    mandala: "Mandala and Pattern style. Symmetrical, intricate, repetitive decorative elements integrated into the subject.",
    anime: "Anime/Manga Line Art style. Clean, thin, uniform lines. Focus on character outlines and minimal background noise. Cel-shaded look."
  };

  // --- COMPLEXITY CONFIGURATION ---
  const complexityConfig: Record<ComplexityLevel, { max: string, min: string }> = {
    low: { max: "5%", min: "1%" },      
    medium: { max: "2%", min: "0.3%" }, 
    high: { max: "0.5%", min: "0.1%" }  
  };

  const selectedStyle = stylePrompts[style];
  const selectedComplexity = complexityConfig[complexity];

  const response = await ai.models.generateContent({
    model: 'gemini-3-pro-image-preview',
    contents: {
      parts: [
        {
          inlineData: {
            data: imageData,
            mimeType: mimeType,
          },
        },
        {
          text: `You are an expert technical illustrator creating a source image for a coloring app.

          TASK: Convert this image into a "${style}" style illustration.
          
          STYLE GUIDELINES:
          ${selectedStyle}
          
          STRICT VISUAL REQUIREMENTS:
          1. **Pre-Colored**: The output must be FULLY COLORED with flat, solid colors.
          2. **Black Outlines**: Every single color region must be separated by a BOLD, PURE BLACK (#000000) stroke.
          3. **NO TEXTURE**: Do not use stippling, hatching, cross-hatching, or noise.
          4. **Segmentation Rules**: 
             - Divide the image into distinct cells.
             - **Max Region Size**: No single region should be larger than ${selectedComplexity.max} of the canvas.
             - **Min Region Size**: No region should be smaller than ${selectedComplexity.min}.
          5. **Color Palette**: Limit to 32-64 distinct colors.
             **CRITICAL**: DO NOT USE DARK COLORS. All fill colors MUST have a luminance greater than 30%. Dark Brown, Dark Navy, Black, etc., are STRICTLY FORBIDDEN for fills. Use lighter, pastel, or vibrant variations instead. The only dark element in the image should be the outlines.
          6. **Resolution**: 2K resolution.
          
          The result should look like a professional coloring page template where the lines are clearly distinguishable from the fill colors.
          `,
        },
      ],
    },
    config: {
      imageConfig: {
        imageSize: "2K",
        aspectRatio: "1:1"
      }
    }
  });

  for (const part of response.candidates?.[0]?.content?.parts || []) {
    if (part.inlineData) {
      return `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`;
    }
  }

  throw new Error("No illustration generated by the AI.");
}
